# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='verification.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12verification.proto\")\n\x13VerificationRequest\x12\x12\n\nuser_token\x18\x01 \x01(\x05\"7\n\x14VerificationResponse\x12\x1f\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\r.UserCategory*3\n\x0cUserCategory\x12\x0c\n\x08RESERVED\x10\x00\x12\n\n\x06\x43LIENT\x10\x01\x12\t\n\x05\x41\x44MIN\x10\x02\x32\x46\n\rVerifications\x12\x35\n\x06Verify\x12\x14.VerificationRequest\x1a\x15.VerificationResponseb\x06proto3'
)

_USERCATEGORY = _descriptor.EnumDescriptor(
  name='UserCategory',
  full_name='UserCategory',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESERVED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLIENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADMIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=122,
  serialized_end=173,
)
_sym_db.RegisterEnumDescriptor(_USERCATEGORY)

UserCategory = enum_type_wrapper.EnumTypeWrapper(_USERCATEGORY)
RESERVED = 0
CLIENT = 1
ADMIN = 2



_VERIFICATIONREQUEST = _descriptor.Descriptor(
  name='VerificationRequest',
  full_name='VerificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_token', full_name='VerificationRequest.user_token', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=63,
)


_VERIFICATIONRESPONSE = _descriptor.Descriptor(
  name='VerificationResponse',
  full_name='VerificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='VerificationResponse.category', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=120,
)

_VERIFICATIONRESPONSE.fields_by_name['category'].enum_type = _USERCATEGORY
DESCRIPTOR.message_types_by_name['VerificationRequest'] = _VERIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['VerificationResponse'] = _VERIFICATIONRESPONSE
DESCRIPTOR.enum_types_by_name['UserCategory'] = _USERCATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationRequest = _reflection.GeneratedProtocolMessageType('VerificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONREQUEST,
  '__module__' : 'verification_pb2'
  # @@protoc_insertion_point(class_scope:VerificationRequest)
  })
_sym_db.RegisterMessage(VerificationRequest)

VerificationResponse = _reflection.GeneratedProtocolMessageType('VerificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONRESPONSE,
  '__module__' : 'verification_pb2'
  # @@protoc_insertion_point(class_scope:VerificationResponse)
  })
_sym_db.RegisterMessage(VerificationResponse)



_VERIFICATIONS = _descriptor.ServiceDescriptor(
  name='Verifications',
  full_name='Verifications',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=175,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='Verifications.Verify',
    index=0,
    containing_service=None,
    input_type=_VERIFICATIONREQUEST,
    output_type=_VERIFICATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERIFICATIONS)

DESCRIPTOR.services_by_name['Verifications'] = _VERIFICATIONS

# @@protoc_insertion_point(module_scope)
